using Artifax.Data;
using Artifax.Models;
using Artifax.Services;
using DotNetEnv;
using Microsoft.EntityFrameworkCore;

// Load environment variables from .env.local file
Env.Load();

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
//Cors
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowReactApp",
        policy =>
        {
                        // Replace with your actual React app's URL/Port
                        policy.WithOrigins("http://localhost:3000", "http://localhost:3001", "http://localhost:5253") 
                  .AllowAnyHeader()
                .AllowAnyMethod()
                .AllowCredentials();
        });
});

builder.Services.AddControllers();

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

// Prefer configured connection string (appsettings/user-secrets), then fall back to DATABASE_* vars.
var connectionString = builder.Configuration.GetConnectionString("ArtifaxDatabase");
Console.WriteLine($"[CRITICAL DEBUG] String starts with: '{connectionString?.Substring(0, Math.Min(connectionString?.Length ?? 0, 10))}'");

if (string.IsNullOrWhiteSpace(connectionString))
{
    var host = Environment.GetEnvironmentVariable("DATABASE_HOST");
    var port = Environment.GetEnvironmentVariable("DATABASE_PORT");
    var database = Environment.GetEnvironmentVariable("DATABASE_NAME");
    var username = Environment.GetEnvironmentVariable("DATABASE_USERNAME");
    var password = Environment.GetEnvironmentVariable("DATABASE_PASSWORD");

    connectionString = $"Host={host};Port={port};Database={database};Username={username};Password={password};SSL Mode=Require;Trust Server Certificate=true";
}

if (string.IsNullOrWhiteSpace(connectionString) || connectionString.Contains("Host=;"))
{
    throw new InvalidOperationException(
        "Database connection is not configured. Set ConnectionStrings:ArtifaxDatabase (user-secrets) or DATABASE_* environment variables.");
}

// (debug prefix removed)

builder.Services.AddDbContext<ArtifaxContext>(options => options.UseNpgsql(connectionString));

// Register the background service for order time tracking
builder.Services.AddHostedService<OrderTimeTrackingService>();

builder.Services.AddDistributedMemoryCache();
builder.Services.AddSession(option => {
    option.IdleTimeout = TimeSpan.FromHours(14);
    option.Cookie.HttpOnly = true;
    option.Cookie.IsEssential = true;
});

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<ArtifaxContext>();
    dbContext.Database.ExecuteSqlRaw(@"
        CREATE TABLE IF NOT EXISTS ""OrderItems"" (
            ""OrderItemID"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""OrderID"" integer NOT NULL,
            ""ItemID"" integer NOT NULL,
            ""Quantity"" integer NOT NULL,
            CONSTRAINT ""FK_OrderItems_Orders_OrderID"" FOREIGN KEY (""OrderID"") REFERENCES ""Orders"" (""OrderID"") ON DELETE CASCADE,
            CONSTRAINT ""FK_OrderItems_Items_ItemID"" FOREIGN KEY (""ItemID"") REFERENCES ""Items"" (""ItemID"") ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS ""IX_OrderItems_ItemID"" ON ""OrderItems"" (""ItemID"");
        CREATE INDEX IF NOT EXISTS ""IX_OrderItems_OrderID"" ON ""OrderItems"" (""OrderID"");

        ALTER TABLE ""Employees"" ADD COLUMN IF NOT EXISTS ""TotpSecret"" text;
        ALTER TABLE ""Employees"" ADD COLUMN IF NOT EXISTS ""TotpEnabled"" boolean NOT NULL DEFAULT false;
        ALTER TABLE ""Employees"" ADD COLUMN IF NOT EXISTS ""RecoveryCodesHash"" text;
        ALTER TABLE ""Employees"" ADD COLUMN IF NOT EXISTS ""FailedLoginAttempts"" integer NOT NULL DEFAULT 0;
        ALTER TABLE ""Employees"" ADD COLUMN IF NOT EXISTS ""LockedUntilUtc"" timestamp with time zone;
        ALTER TABLE ""Employees"" ADD COLUMN IF NOT EXISTS ""FailedOtpAttempts"" integer NOT NULL DEFAULT 0;
        ALTER TABLE ""Employees"" ADD COLUMN IF NOT EXISTS ""OtpLockedUntilUtc"" timestamp with time zone;
    ");

    dbContext.Database.ExecuteSqlRaw(@"
        SELECT setval(
            pg_get_serial_sequence('""Branches""', 'BranchID'),
            COALESCE((SELECT MAX(""BranchID"") FROM ""Branches""), 1),
            true
        );

        SELECT setval(
            pg_get_serial_sequence('""Employees""', 'EmployeeId'),
            COALESCE((SELECT MAX(""EmployeeId"") FROM ""Employees""), 1),
            true
        );
    ");

    if (app.Environment.IsDevelopment())
    {
        const string defaultBranchName = "Main Branch";
        const string defaultAdminEmail = "admin@artifax.local";
        const string defaultAdminName = "Dev Admin";
        const string defaultAdminPassword = "Artifax123!";
        const string defaultEmployeeEmail = "employee@artifax.local";
        const string defaultEmployeeName = "Dev Employee";
        const string defaultEmployeePassword = "Artifax123!";

        var defaultBranch = await dbContext.Branches.FirstOrDefaultAsync(branch => branch.BranchName == defaultBranchName);
        if (defaultBranch == null)
        {
            defaultBranch = new Branch { BranchName = defaultBranchName };
            dbContext.Branches.Add(defaultBranch);
            await dbContext.SaveChangesAsync();
        }

        var defaultAdmin = await dbContext.Employees.FirstOrDefaultAsync(employee => employee.EmployeeEmail == defaultAdminEmail);
        if (defaultAdmin == null)
        {
            defaultAdmin = new Employee
            {
                BranchId = defaultBranch.BranchID,
                EmployeeEmail = defaultAdminEmail,
                EmployeeName = defaultAdminName,
                EmployeePasswordHash = BCrypt.Net.BCrypt.HashPassword(defaultAdminPassword),
                EmployeeLevel = "Admin",
                TotpEnabled = false,
            };

            dbContext.Employees.Add(defaultAdmin);
            await dbContext.SaveChangesAsync();
            Console.WriteLine($"[DEV SEED] Created default admin {defaultAdminEmail} with password {defaultAdminPassword}");
        }

        var defaultEmployee = await dbContext.Employees.FirstOrDefaultAsync(employee => employee.EmployeeEmail == defaultEmployeeEmail);
        if (defaultEmployee == null)
        {
            defaultEmployee = new Employee
            {
                BranchId = defaultBranch.BranchID,
                EmployeeEmail = defaultEmployeeEmail,
                EmployeeName = defaultEmployeeName,
                EmployeePasswordHash = BCrypt.Net.BCrypt.HashPassword(defaultEmployeePassword),
                EmployeeLevel = "Employee",
                TotpEnabled = false,
            };

            dbContext.Employees.Add(defaultEmployee);
            await dbContext.SaveChangesAsync();
            Console.WriteLine($"[DEV SEED] Created default employee {defaultEmployeeEmail} with password {defaultEmployeePassword}");
        }
    }
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
    app.MapOpenApi();
}

app.UseCors("AllowReactApp");

app.UseHttpsRedirection();

app.UseSession();

app.Use(async (context, next) =>
{
    if (HttpMethods.IsOptions(context.Request.Method))
    {
        await next();
        return;
    }

    var path = context.Request.Path;
    var isApiRequest = path.StartsWithSegments("/api");
    var isAuthExempt =
        path.StartsWithSegments("/api/User/employees/login") ||
        path.StartsWithSegments("/api/User/employees/login/verify") ||
        path.StartsWithSegments("/api/User/seed/admin") ||
        path.StartsWithSegments("/api/User/seed/employee") ||
        path.StartsWithSegments("/api/User/dev");

    if (isApiRequest && !isAuthExempt)
    {
        var userLevel = context.Session.GetString("UserLevel");
        if (string.IsNullOrWhiteSpace(userLevel))
        {
            context.Response.StatusCode = StatusCodes.Status401Unauthorized;
            await context.Response.WriteAsJsonAsync(new { message = "Authentication required." });
            return;
        }
    }

    await next();
});

app.UseAuthorization();

app.MapControllers();

app.Run();
