export const historyData = [
  { id: 'J-2515', name: 'table', date: '2024/02/05', qty: 120, min: 20, operator: 'Mike', status: 'Crafted', type: 'furniture', location: 'Warehouse A' },
  { id: 'J-2516', name: 'A4 Sketch book', date: '2024/02/05', qty: 4, min: 15, operator: 'Jim', status: 'Cancelled', type: 'stationery', location: 'Studio 1' },
  { id: 'MET-003', name: 'Aluminium Sheet', date: '2024/02/05', qty: 88, min: 10, operator: 'Dan', status: 'Crafted', type: 'metal', location: 'Warehouse B' },
  { id: 'MET-004', name: 'Titanium Bar', date: '2024/02/05', qty: 32, min: 5, operator: 'Bill', status: 'Crafted', type: 'metal', location: 'Warehouse B' },
  { id: 'MET-005', name: 'Spring Coil', date: '2024/02/05', qty: 200, min: 30, operator: 'Dick', status: 'Crafted', type: 'metal', location: 'Workshop 3' },
  { id: 'MET-006', name: 'Stainless Pipe', date: '2024/02/05', qty: 55, min: 10, operator: 'Earl', status: 'Crafted', type: 'metal', location: 'Warehouse B' },
  { id: 'MET-007', name: 'Zinc Plate', date: '2024/02/05', qty: 40, min: 8, operator: 'Pan', status: 'Crafted', type: 'metal', location: 'Warehouse C' },
  { id: 'FST-001', name: 'Bolt Set M8', date: '2024/02/05', qty: 500, min: 50, operator: 'Kim', status: 'Crafted', type: 'fastener', location: 'Warehouse A' },
  { id: 'FST-002', name: 'Hex Nut M10', date: '2024/02/05', qty: 320, min: 40, operator: 'Andre', status: 'Crafted', type: 'fastener', location: 'Workshop 1' },
  { id: 'FST-003', name: 'Rivet Set 4mm', date: '2024/02/05', qty: 180, min: 25, operator: 'Goku', status: 'Crafted', type: 'fastener', location: 'Workshop 1' },
  { id: 'FST-004', name: 'Thread Tap M6', date: '2024/02/05', qty: 60, min: 10, operator: 'Paul', status: 'Crafted', type: 'fastener', location: 'Workshop 2' },
  { id: 'PLS-008', name: 'Plastic Case', date: '2024/02/06', qty: 150, min: 20, operator: 'Andy', status: 'Crafted', type: 'plastic', location: 'Workshop B' },
  { id: 'ELC-009', name: 'Circuit Board', date: '2024/02/06', qty: 60, min: 40, operator: 'Sara', status: 'Crafted', type: 'electronics', location: 'Electronics Bay' },
  { id: 'ELC-010', name: 'Sensor Lens', date: '2024/02/06', qty: 42, min: 35, operator: 'Tom', status: 'Cancelled', type: 'electronics', location: 'Lab 2' },
  { id: 'TXT-011', name: 'Canvas Roll', date: '2024/02/06', qty: 90, min: 55, operator: 'Lena', status: 'Crafted', type: 'textile', location: 'Studio 2' },
  { id: 'FUR-012', name: 'Chair Frame', date: '2024/02/06', qty: 24, min: 120, operator: 'Max', status: 'Crafted', type: 'furniture', location: 'Warehouse C' },
  { id: 'GLS-013', name: 'Safety Glass', date: '2024/02/06', qty: 130, min: 25, operator: 'Julia', status: 'Crafted', type: 'glass', location: 'Warehouse B' },
  { id: 'FUR-014', name: 'Shelf Panel', date: '2024/02/06', qty: 80, min: 70, operator: 'Eric', status: 'Cancelled', type: 'furniture', location: 'Warehouse A' },
  { id: 'FST-015', name: 'Spacer Ring', date: '2024/02/07', qty: 220, min: 10, operator: 'Nina', status: 'Crafted', type: 'fastener', location: 'Workshop A' },
  { id: 'MET-016', name: 'Copper Tube', date: '2024/02/07', qty: 65, min: 15, operator: 'Carla', status: 'Cancelled', type: 'metal', location: 'Warehouse B' },
  { id: 'PLS-017', name: 'Molded Handle', date: '2024/02/07', qty: 180, min: 45, operator: 'Alex', status: 'Crafted', type: 'plastic', location: 'Workshop C' },
  { id: 'ELC-018', name: 'Power Cable', date: '2024/02/07', qty: 210, min: 12, operator: 'Mike', status: 'Crafted', type: 'electronics', location: 'Warehouse B' },
  { id: 'TXT-019', name: 'Fabric Strip', date: '2024/02/07', qty: 300, min: 20, operator: 'Kim', status: 'Crafted', type: 'textile', location: 'Studio 1' },
  { id: 'FST-020', name: 'Lock Washer', date: '2024/02/07', qty: 140, min: 35, operator: 'Raj', status: 'Crafted', type: 'fastener', location: 'Workshop B' },
  { id: 'MET-021', name: 'Aluminum Rod', date: '2024/02/07', qty: 48, min: 25, operator: 'Sam', status: 'Crafted', type: 'metal', location: 'Warehouse C' },
  { id: 'GLS-022', name: 'Acrylic Sheet', date: '2024/02/07', qty: 72, min: 18, operator: 'Dee', status: 'Cancelled', type: 'glass', location: 'Warehouse B' }
];